### ISSUE TITLE
Moving the finished note to something other than _posts

### ISSUE THREAD

**Issue by gael-vanderlee** [songkg7/o2#363]
**Is your feature request related to a problem? Please describe.**
My personal website doesn't just have posts, but also projects, news, pages etc. This means I need to move the generated markdown file to the right folder

**Describe the solution you'd like**
Ideally, my "ready" folder would have subfolders "_post" or "_projects", matching those of my jekyll website. The notes put in those folders would be moved to the corresponding folder (if it exists) in the jekyll project.
A less flexible option would be to make the output folder a plugin option.

**Comment by pedrobiqua** [comment]
I really liked the idea. I was looking at the project's issues and came across this feature request. I also need something like this and would be willing to implement it, of course, with the proper authorization from the repository maintainers. @songkg7 I would be happy to implement this. 😁
