### ISSUE TITLE
Add Support for `relative_url` in Images during Conversion to Jekyll

### ISSUE THREAD

**Issue by pedrobiqua** [songkg7/o2#405]
**Feature Request**

I’m currently using `baseurl` in my Jekyll blog as it’s necessary for the proper functioning of the site. As a result, I need to use the `relative_url` function to ensure images in the `assets/img` directory are properly referenced. An example would be:

```markdown
![text]({{ "/assets/img/photo.jpeg" | relative_url }})
```

Without this conversion, the images are not loaded correctly on the production server (in my case, GitHub Pages). It would be very helpful if this support could be included in the image conversion, ensuring they are properly formatted for Jekyll.

The plugin is really great, and I’m already using it to write my blog in Obsidian, which helps bring everything together in one place. This is the only manual step I have to take, and it would be awesome to automate it!

**Comment by songkg7** [comment]
Thanks for your interest.

I will work on it ASAP.

**Comment by pedrobiqua** [comment]
Thanks Haril Song, your plugin has been helping me a lot with writing my blog. If you need help, contact me. I know a little bit of typescript, but i never did a obsidian plugin.
